#include "func.c"

#define N_COLORS 32

typedef enum {
	FG_BLACK = 0,
	FG_DARK_RED = FOREGROUND_RED,
	FG_DARK_GREEN = FOREGROUND_GREEN,
	FG_DARK_BLUE = FOREGROUND_BLUE,
	FG_LIGHT_GRAY = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN,
	FG_DARK_AQUA = FOREGROUND_BLUE | FOREGROUND_GREEN,
	FG_PURPLE = FOREGROUND_RED | FOREGROUND_BLUE,
	FG_DARK_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,

	FG_GRAY = 0 | FOREGROUND_INTENSITY,
	FG_RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
	FG_GREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	FG_BLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	FG_WHITE = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	FG_AQUA = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	FG_PINK = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	FG_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,


	BG_BLACK = 0,
	BG_DARK_RED = BACKGROUND_RED,
	BG_DARK_GREEN = BACKGROUND_GREEN,
	BG_DARK_BLUE = BACKGROUND_BLUE,
	BG_LIGHT_GRAY = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN,
	BG_DARK_AQUA = BACKGROUND_BLUE | BACKGROUND_GREEN,
	BG_PURPLE = BACKGROUND_RED | BACKGROUND_BLUE,
	BG_DARK_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN,

	BG_GRAY = 0 | BACKGROUND_INTENSITY,
	BG_RED = BACKGROUND_RED | BACKGROUND_INTENSITY,
	BG_GREEN = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	BG_BLUE = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	BG_WHITE = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	BG_AQUA = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	BG_PINK = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	BG_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY
} COLORS;

const oz_byte _COLOR_ARRAY[N_COLORS] = {
	FG_BLACK,
	FG_DARK_RED,
	FG_DARK_GREEN,
	FG_DARK_BLUE,
	FG_LIGHT_GRAY,
	FG_DARK_AQUA,
	FG_PURPLE,
	FG_DARK_YELLOW,

	FG_GRAY,
	FG_RED,
	FG_GREEN,
	FG_BLUE,
	FG_WHITE,
	FG_AQUA,
	FG_PINK,
	FG_YELLOW,

	BG_BLACK,
	BG_DARK_RED,
	BG_DARK_GREEN,
	BG_DARK_BLUE,
	BG_LIGHT_GRAY,
	BG_DARK_AQUA,
	BG_PURPLE,
	BG_DARK_YELLOW,

	BG_GRAY,
	BG_RED,
	BG_GREEN,
	BG_BLUE,
	BG_WHITE,
	BG_AQUA,
	BG_PINK,
	BG_YELLOW
};

typedef enum {
	FG_BLACK_ID = 0,
	FG_DARK_RED_ID,
	FG_DARK_GREEN_ID,
	FG_DARK_BLUE_ID,
	FG_LIGHT_GRAY_ID,
	FG_DARK_AQUA_ID,
	FG_PURPLE_ID,
	FG_DARK_YELLOW_ID,

	FG_GRAY_ID,
	FG_RED_ID,
	FG_GREEN_ID,
	FG_BLUE_ID,
	FG_WHITE_ID,
	FG_AQUA_ID,
	FG_PINK_ID,
	FG_YELLOW_ID,

	BG_BLACK_ID,
	BG_DARK_RED_ID,
	BG_DARK_GREEN_ID,
	BG_DARK_BLUE_ID,
	BG_LIGHT_GRAY_ID,
	BG_DARK_AQUA_ID,
	BG_PURPLE_ID,
	BG_DARK_YELLOW_ID,

	BG_GRAY_ID,
	BG_RED_ID,
	BG_GREEN_ID,
	BG_BLUE_ID,
	BG_WHITE_ID,
	BG_AQUA_ID,
	BG_PINK_ID,
	BG_YELLOW_ID
} COLOR_IDS;

typedef struct _color {
	COLORS bg_color;
	COLORS fg_color;
	bool transparent_bg;
} oz_Color;

struct {
	const struct _color BLACK_ON_BLACK;
	const struct _color WHITE_ON_BLACK;
	const struct _color PURPLE_ON_GRAY;
	const struct _color DARK_GREEN_T;
	const struct _color DARK_RED_ON_DARK_AQUA;
	const struct _color DARK_GREEN_ON_BLACK;
	const struct _color PURPLE_ON_LIGHT_GRAY;
	const struct _color GREEN_ON_BLACK;
	const struct _color PINK_ON_WHITE;
	const struct _color PINK_ON_BLACK;
	const struct _color GREEN_ON_DARK_GREEN;
	const struct _color PURPLE_ON_BLACK;
	const struct _color LIGHT_GRAY_ON_GRAY;
	const struct _color BLUE_ON_DARK_AQUA;
	const struct _color BLACK_ON_AQUA;
	const struct _color DARK_BLUE_ON_DARK_AQUA;
	const struct _color BLACK_ON_DARK_RED;
	const struct _color GRAY_ON_BLUE;
	const struct _color GRAY_ON_DARK_BLUE;
	const struct _color WHITE_ON_DARK_BLUE;
	const struct _color DARK_GREEN_ON_LIGHT_GRAY;
	const struct _color DARK_GREEN_ON_GRAY;
	const struct _color LIGHT_GRAY_ON_BLACK;
	const struct _color YELLOW_ON_DARK_RED;
	const struct _color YELLOW_ON_DARK_YELLOW;
	const struct _color DARK_YELLOW_ON_YELLOW;
	const struct _color BLACK_ON_DARK_AQUA;
} DefaultColors = {
	{BG_BLACK, FG_BLACK, false},
	{BG_BLACK, FG_WHITE, false},
	{BG_GRAY, FG_PURPLE, false},
	{BG_BLACK, FG_DARK_GREEN, true},
	{BG_DARK_AQUA, FG_DARK_RED, false},
	{BG_BLACK, FG_DARK_GREEN, false},
	{BG_LIGHT_GRAY, FG_PURPLE, false},
	{BG_BLACK, FG_GREEN, false},
	{BG_WHITE, FG_PINK, false},
	{BG_BLACK, FG_PINK, false},
	{BG_DARK_GREEN, FG_GREEN, false},
	{BG_BLACK, FG_PURPLE, false},
	{BG_GRAY, FG_LIGHT_GRAY, false},
	{BG_DARK_AQUA, FG_BLUE, false},
	{BG_AQUA, FG_BLACK, false},
	{BG_DARK_AQUA, FG_DARK_BLUE, false},
	{BG_DARK_RED, FG_BLACK, false},
	{BG_BLUE, FG_GRAY, false},
	{BG_DARK_BLUE, FG_GRAY, false},
	{BG_DARK_BLUE, FG_WHITE, false},
	{BG_LIGHT_GRAY, FG_DARK_GREEN, false},
	{BG_GRAY, FG_DARK_GREEN, false},
	{BG_BLACK, FG_LIGHT_GRAY, false},
	{BG_DARK_RED, FG_YELLOW, false},
	{BG_DARK_YELLOW, FG_YELLOW, false},
	{BG_YELLOW, FG_DARK_YELLOW, false},
	{BG_DARK_AQUA, FG_BLACK, false}
};

oz_byte oz_getColorIndex(COLORS color)
{
	for (oz_byte i = 0; i < N_COLORS; i++)
	{
		if (_COLOR_ARRAY[i] == color)
			return i;
	}
	return 0;
}

COLORS oz_getColorFromIndex(int index)
{
	if (index < 0 || index >= N_COLORS)
		return 0;
	return _COLOR_ARRAY[index];
}
